version: '3.8'

services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-customer-support
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=sqlite:///./customer_support.db
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./customer_support.db:/app/customer_support.db
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 10 &&
        echo 'Pulling Mistral model if not exists...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"mistral\"}' &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: