version: '3.8'

services:
  # Main application (using host's Ollama)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-customer-support
    ports:
      - "8001:8000"  # Map to port 8001 on host to avoid conflict
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434  # Use host's Ollama
      - OLLAMA_MODEL=mistral
      - DATABASE_URL=sqlite:///./data/customer_support.db
      - LOG_LEVEL=INFO
      - KNOWLEDGE_BASE_PATH=./data/knowledge_base.md
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host
    # Run as root to avoid permission issues
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge